### ISSUE TITLE
Buffer overrun

### ISSUE THREAD

**Issue by larsiusprime** [nick-paul/LightMask#1]
https://github.com/nick-paul/LightMask/blob/a9c935442c9321445b757b5e0289de2682812172/LightMask.hpp#L132

On this line, I believe the value idx returns is equal to the length of the array itself, which is out of bounds. I encountered this when porting your implementation to Haxe as a learning exercise:
https://github.com/larsiusprime/HxLightMask

**Comment by nick-paul** [comment]
Was playing with this project again and found the issue you ran into. It was an off-by-one error in the loop. Fixed in this commit: d36297024f9e1f20a5fe13974f6e1cb59746fddf
